UPDATE workerUPDATE worker
SET userName = 'sa',
    fullName = 'Lukas Grihander',
    password = 'sd',
    sinceDate = '2024-05-07',
    ss = 12345678 ', dni = ' 33409897s ', idSection = 0, idRank = 0, address = ' fd ', telNum = ' as ', email = ' li @ed.ll ', contact = ' fa ', docFolder = ' / home / miquel / Escritorio / project1DAM / doc_empleados / Lukas ', active = ' YES ' WHERE idWorker = 4
SET userName = ' sa ' fullName = ' Lukas Grihander ' password = ' sd ' sinceDate = ' 2024 -05 -07 ' ss = 12345678 ' dni = ' 33409897s ' idSection = 0 idRank = 0 address = ' fd ' telNum = ' as ' email = ' li @ed.ll ' contact = ' fa ' docFolder = ' / home / miquel / Escritorio / project1DAM / doc_empleados / Lukas ' active = ' NO '
WHERE idWorker = 4